---
version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      --web.enable-lifecycle
      --config.file=/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
  influxdb:
    image: influxdb:1.8.5
    ports:
      - '8086:8086'
    volumes:
      - 'influxdb:/var/lib/influxdb'
    environment:
      INFLUXDB_DB: prometheus

volumes:
  influxdb:
    driver: local