---
version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus/data:/prometheus/data'
    command:
      --web.enable-lifecycle
      --web.enable-admin-api
      --config.file=/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports:
      - '8428:8428'
    volumes:
      - 'victoriametrics:/victoria-metrics-data'
    command:
      -storageDataPath=/victoria-metrics-data
      -retentionPeriod=30d
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana

volumes:
  victoriametrics:
    driver: local