version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
  blackbox_exporter:
    image: quay.io/prometheus/blackbox-exporter
    volumes:
      - './blackbox.yml:/etc/blackbox_exporter/config.yml'
    ports:
      - '9115:9115'