---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mysql" # To get metrics about the mysql exporter’s targets
    static_configs:
      - targets:
          # All mysql hostnames or unix sockets to monitor.
          - docker.for.mac.localhost:9104

